<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit95515f2c37124f431b9f954c7f5fda21
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Phpml\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Phpml\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-ai/php-ml/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'S' => 
        array (
            'Sastrawi\\' => 
            array (
                0 => __DIR__ . '/..' . '/sastrawi/sastrawi/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit95515f2c37124f431b9f954c7f5fda21::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit95515f2c37124f431b9f954c7f5fda21::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit95515f2c37124f431b9f954c7f5fda21::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
